language: node_js
node_js: '12'
cache: yarn

env:
  global:
    - NODE_ENV=test

addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN

install:
  - yarn install

script:
  - yarn build
  - yarn coveralls

after_success: yarn coverage
